[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "budgy"
version = "2.0.2"
description = "budget managing application"
authors = [{name = "Elias Rodkey", email = "elias.rodkey@gmail.com"}]
license = {text = "All Rights Reserved"}
dependencies = [
    "requests",
    "numpy",
    "pandas",
    "sqlalchemy",
    "fastapi",
    "uvicorn",
    "pydantic",
    "pleasant_loggers",
    "pleasant_database",
    "anthropic"
]

[project.optional-dependencies]
dev = ["pytest"]