// Mirrors CATEGORY_MAPPING from budgy/utils/analysis_utils.py
// Keys are primaryCategory values; values are arrays of detailedCategory options.
// Replace with an API call when the backend endpoint is available.

export const CATEGORY_MAPPING: Record<string, string[]> = {
  "Income": [
    "Wages",
    "Dividends",
    "Interest",
    "Benefits & pension",
    "Tax refunds",
    "Unemployment",
    "Other income",
  ],
  "Transfers": [
    "Account transfers",
    "Investment transfers",
    "Savings transfers",
    "Cash deposits",
    "Cash withdrawals",
    "Loans & cash advances",
    "Person to person payments",
    "Other transfers",
  ],
  "Debt payments": [
    "Credit card payments",
    "Auto loan payments",
    "Student loan payments",
    "Personal loan payments",
    "Other debt payments",
  ],
  "Investments": [
    "Buy",
    "Sell",
  ],
  "Bank fees": [
    "Atm fees",
    "Foreign transaction fees",
    "Insufficient funds",
    "Interest charge",
    "Late fees",
    "Wire fees",
    "Overdraft fees",
    "Other bank fees",
  ],
  "Food & drink": [
    "Restaurants & bars",
    "Groceries",
    "Coffee shops",
    "Liquor stores",
    "Other food & drink",
  ],
  "Shopping": [
    "Clothing & accessories",
    "Electronics",
    "Pet supplies",
    "Gifts",
    "Office supplies",
    "Sports & outdoors",
    "Retail",
    "Convenience stores",
    "Hair & beauty",
    "Tabacco & vape",
    "Other shopping",
  ],
  "Housing & utilities": [
    "Rent",
    "Mortgage payments",
    "Home improvement & repairs",
    "Phone & internet",
    "Gas & electricity",
    "Water sewer & garbage",
    "Security",
    "Hoa fee",
    "Property tax",
    "Other housing & utilities",
  ],
  "Health & wellness": [
    "Medical",
    "Pharmacy",
    "Dental",
    "Vision",
    "Nursing",
    "Fitness",
    "Personal care",
    "Other health & wellness",
  ],
  "Entertainment": [
    "Gambling",
    "Books & news",
    "Movies & tv",
    "Music & audio",
    "Games",
    "Events & recreation",
    "Other entertainment",
  ],
  "Insurance": [
    "Life insurance",
    "Health insurance",
    "Auto insurance",
    "Home insurance",
    "Other insurance",
  ],
  "Services": [
    "Household services",
    "Education services",
    "Veterinary services",
    "Childcare services",
    "Digital services",
    "Legal services",
    "Financial services",
    "Shipping",
    "Moving & storage",
    "Other services",
  ],
  "Transportation": [
    "Gas & ev charging",
    "Car services",
    "Public transit",
    "Taxi & ride shares",
    "Parking & tolls",
    "Other transportation",
  ],
  "Travel": [
    "Flights",
    "Hotels",
    "Rental cars",
    "Other travel",
  ],
  "Government & charity": [
    "Tax payments",
    "Government fees",
    "Charity",
    "Other government & charity",
  ],
  "Other": [],
};

// All detailed categories in a flat sorted list, for use when no primary category is selected.
export const ALL_DETAILED_CATEGORIES: string[] = Object.values(CATEGORY_MAPPING)
  .flat()
  .sort();
