#!python3
"""
backend.database_modules.models.summaries.py -
Contains ORM table definitions, database managers, and CSV column mappings for budgy summaries db table.

Classes:
    - SummariesTable: ORM class representing the summaries table in the database.

Variables:
    - summary_columns: List of Column namedtuples mapping CSV headers to TransactionsTable columns
        with type conversion functions for transaction data import.
"""
# Standard library imports

# Custom imports
# TODO: Add ForeignKey to local_db import ESQLDataTypes
from sqlalchemy import ForeignKey, UniqueConstraint, Column, Float, Integer, DateTime
from pleasant_database import BaseTable

# Local imports
from .common import Field

# initialize module logger
import logging
logger = logging.getLogger(__name__)



class SummariesTable(BaseTable):
    """
    Class representing the summaries table in the database.
    This table stores all the summary spending data calculated from the transactions database.

    Database Structure:
        table name: summaries
    Columns:
        - id: primary key, autoincremented. unique per row
        - date: DateTime
        - month: integer (1-12)
        - year: integer
        - budget_id: integer, tied to budgets table
        - PrimaryCateogry category names using as_snake_case_headers method, counts, averages, and totals.
        - DetailedCateogry category names using as_snake_case_headers method, counts, averages, and totals.
    """

    __tablename__ = "summaries"

    # TODO: Consider using setattr on a loop instead of this ridiculout number of column definitions!
    __table_args__ = (
        UniqueConstraint('month', 'year', name='month_of_summary'),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime)
    month = Column(Integer)
    year = Column(Integer)
    budget_id = Column(Integer, ForeignKey("budgets.id"), nullable=False)

    # Sum columns for each category - used for calculating total spending in each category for the month
    sum_income = Column(Float, default=0.0)
    sum_transfers = Column(Float, default=0.0)
    sum_debt_payments = Column(Float, default=0.0)
    sum_investments = Column(Float, default=0.0)
    sum_bank_fees = Column(Float, default=0.0)
    sum_food_and_drink = Column(Float, default=0.0)
    sum_shopping = Column(Float, default=0.0)
    sum_housing_and_utilities = Column(Float, default=0.0)
    sum_health_and_wellness = Column(Float, default=0.0)
    sum_entertainment = Column(Float, default=0.0)
    sum_insurance = Column(Float, default=0.0)
    sum_services = Column(Float, default=0.0)
    sum_transportation = Column(Float, default=0.0)
    sum_travel = Column(Float, default=0.0)
    sum_government_and_charity = Column(Float, default=0.0)
    sum_other = Column(Float, default=0.0)
    sum_wages = Column(Float, default=0.0)
    sum_dividends = Column(Float, default=0.0)
    sum_interest = Column(Float, default=0.0)
    sum_benefits_and_pension = Column(Float, default=0.0)
    sum_tax_refunds = Column(Float, default=0.0)
    sum_unemployment = Column(Float, default=0.0)
    sum_other_income = Column(Float, default=0.0)
    sum_account_transfers = Column(Float, default=0.0)
    sum_investment_transfers = Column(Float, default=0.0)
    sum_savings_transfers = Column(Float, default=0.0)
    sum_cash_deposits = Column(Float, default=0.0)
    sum_cash_withdrawals = Column(Float, default=0.0)
    sum_loans_and_cash_advances = Column(Float, default=0.0)
    sum_person_to_person_payments = Column(Float, default=0.0)
    sum_other_transfers = Column(Float, default=0.0)
    sum_credit_card_payments = Column(Float, default=0.0)
    sum_auto_loan_payments = Column(Float, default=0.0)
    sum_student_loan_payments = Column(Float, default=0.0)
    sum_personal_loan_payments = Column(Float, default=0.0)
    sum_other_debt_payments = Column(Float, default=0.0)
    sum_buy = Column(Float, default=0.0)
    sum_sell = Column(Float, default=0.0)
    sum_atm_fees = Column(Float, default=0.0)
    sum_foreign_transaction_fees = Column(Float, default=0.0)
    sum_insufficient_funds = Column(Float, default=0.0)
    sum_interest_charge = Column(Float, default=0.0)
    sum_late_fees = Column(Float, default=0.0)
    sum_wire_fees = Column(Float, default=0.0)
    sum_overdraft_fees = Column(Float, default=0.0)
    sum_other_bank_fees = Column(Float, default=0.0)
    sum_restaurants_and_bars = Column(Float, default=0.0)
    sum_groceries = Column(Float, default=0.0)
    sum_coffee_shops = Column(Float, default=0.0)
    sum_liquor_stores = Column(Float, default=0.0)
    sum_other_food_and_drink = Column(Float, default=0.0)
    sum_clothing_and_accessories = Column(Float, default=0.0)
    sum_electronics = Column(Float, default=0.0)
    sum_pet_supplies = Column(Float, default=0.0)
    sum_gifts = Column(Float, default=0.0)
    sum_office_supplies = Column(Float, default=0.0)
    sum_sports_and_outdoors = Column(Float, default=0.0)
    sum_retail = Column(Float, default=0.0)
    sum_convenience_stores = Column(Float, default=0.0)
    sum_hair_and_beauty = Column(Float, default=0.0)
    sum_tabacco_and_vape = Column(Float, default=0.0)
    sum_other_shopping = Column(Float, default=0.0)
    sum_rent = Column(Float, default=0.0)
    sum_mortgage_payments = Column(Float, default=0.0)
    sum_home_improvement_and_repairs = Column(Float, default=0.0)
    sum_phone_and_internet = Column(Float, default=0.0)
    sum_gas_and_electricity = Column(Float, default=0.0)
    sum_water_sewer_and_garbage = Column(Float, default=0.0)
    sum_security = Column(Float, default=0.0)
    sum_hoa_fee = Column(Float, default=0.0)
    sum_property_tax = Column(Float, default=0.0)
    sum_other_housing_and_utilities = Column(Float, default=0.0)
    sum_medical = Column(Float, default=0.0)
    sum_pharmacy = Column(Float, default=0.0)
    sum_dental = Column(Float, default=0.0)
    sum_vision = Column(Float, default=0.0)
    sum_nursing = Column(Float, default=0.0)
    sum_fitness = Column(Float, default=0.0)
    sum_personal_care = Column(Float, default=0.0)
    sum_other_health_and_wellness = Column(Float, default=0.0)
    sum_gambling = Column(Float, default=0.0)
    sum_books_and_news = Column(Float, default=0.0)
    sum_movies_and_tv = Column(Float, default=0.0)
    sum_music_and_audio = Column(Float, default=0.0)
    sum_games = Column(Float, default=0.0)
    sum_events_and_recreation = Column(Float, default=0.0)
    sum_other_entertainment = Column(Float, default=0.0)
    sum_life_insurance = Column(Float, default=0.0)
    sum_health_insurance = Column(Float, default=0.0)
    sum_auto_insurance = Column(Float, default=0.0)
    sum_home_insurance = Column(Float, default=0.0)
    sum_other_insurance = Column(Float, default=0.0)
    sum_household_services = Column(Float, default=0.0)
    sum_education_services = Column(Float, default=0.0)
    sum_veterinary_services = Column(Float, default=0.0)
    sum_childcare_services = Column(Float, default=0.0)
    sum_digital_services = Column(Float, default=0.0)
    sum_legal_services = Column(Float, default=0.0)
    sum_financial_services = Column(Float, default=0.0)
    sum_shipping = Column(Float, default=0.0)
    sum_moving_and_storage = Column(Float, default=0.0)
    sum_other_services = Column(Float, default=0.0)
    sum_gas_and_ev_charging = Column(Float, default=0.0)
    sum_car_services = Column(Float, default=0.0)
    sum_public_transit = Column(Float, default=0.0)
    sum_taxi_and_ride_shares = Column(Float, default=0.0)
    sum_parking_and_tolls = Column(Float, default=0.0)
    sum_other_transportation = Column(Float, default=0.0)
    sum_flights = Column(Float, default=0.0)
    sum_hotels = Column(Float, default=0.0)
    sum_rental_cars = Column(Float, default=0.0)
    sum_other_travel = Column(Float, default=0.0)
    sum_tax_payments = Column(Float, default=0.0)
    sum_government_fees = Column(Float, default=0.0)
    sum_charity = Column(Float, default=0.0)
    sum_other_government_and_charity = Column(Float, default=0.0)

    # Mean columns for each category - used for calculating average transaction amounts in each category
    mean_income = Column(Float, default=0.0)
    mean_transfers = Column(Float, default=0.0)
    mean_debt_payments = Column(Float, default=0.0)
    mean_investments = Column(Float, default=0.0)
    mean_bank_fees = Column(Float, default=0.0)
    mean_food_and_drink = Column(Float, default=0.0)
    mean_shopping = Column(Float, default=0.0)
    mean_housing_and_utilities = Column(Float, default=0.0)
    mean_health_and_wellness = Column(Float, default=0.0)
    mean_entertainment = Column(Float, default=0.0)
    mean_insurance = Column(Float, default=0.0)
    mean_services = Column(Float, default=0.0)
    mean_transportation = Column(Float, default=0.0)
    mean_travel = Column(Float, default=0.0)
    mean_government_and_charity = Column(Float, default=0.0)
    mean_other = Column(Float, default=0.0)
    mean_wages = Column(Float, default=0.0)
    mean_dividends = Column(Float, default=0.0)
    mean_interest = Column(Float, default=0.0)
    mean_benefits_and_pension = Column(Float, default=0.0)
    mean_tax_refunds = Column(Float, default=0.0)
    mean_unemployment = Column(Float, default=0.0)
    mean_other_income = Column(Float, default=0.0)
    mean_account_transfers = Column(Float, default=0.0)
    mean_investment_transfers = Column(Float, default=0.0)
    mean_savings_transfers = Column(Float, default=0.0)
    mean_cash_deposits = Column(Float, default=0.0)
    mean_cash_withdrawals = Column(Float, default=0.0)
    mean_loans_and_cash_advances = Column(Float, default=0.0)
    mean_person_to_person_payments = Column(Float, default=0.0)
    mean_other_transfers = Column(Float, default=0.0)
    mean_credit_card_payments = Column(Float, default=0.0)
    mean_auto_loan_payments = Column(Float, default=0.0)
    mean_student_loan_payments = Column(Float, default=0.0)
    mean_personal_loan_payments = Column(Float, default=0.0)
    mean_other_debt_payments = Column(Float, default=0.0)
    mean_buy = Column(Float, default=0.0)
    mean_sell = Column(Float, default=0.0)
    mean_atm_fees = Column(Float, default=0.0)
    mean_foreign_transaction_fees = Column(Float, default=0.0)
    mean_insufficient_funds = Column(Float, default=0.0)
    mean_interest_charge = Column(Float, default=0.0)
    mean_late_fees = Column(Float, default=0.0)
    mean_wire_fees = Column(Float, default=0.0)
    mean_overdraft_fees = Column(Float, default=0.0)
    mean_other_bank_fees = Column(Float, default=0.0)
    mean_restaurants_and_bars = Column(Float, default=0.0)
    mean_groceries = Column(Float, default=0.0)
    mean_coffee_shops = Column(Float, default=0.0)
    mean_liquor_stores = Column(Float, default=0.0)
    mean_other_food_and_drink = Column(Float, default=0.0)
    mean_clothing_and_accessories = Column(Float, default=0.0)
    mean_electronics = Column(Float, default=0.0)
    mean_pet_supplies = Column(Float, default=0.0)
    mean_gifts = Column(Float, default=0.0)
    mean_office_supplies = Column(Float, default=0.0)
    mean_sports_and_outdoors = Column(Float, default=0.0)
    mean_retail = Column(Float, default=0.0)
    mean_convenience_stores = Column(Float, default=0.0)
    mean_hair_and_beauty = Column(Float, default=0.0)
    mean_tabacco_and_vape = Column(Float, default=0.0)
    mean_other_shopping = Column(Float, default=0.0)
    mean_rent = Column(Float, default=0.0)
    mean_mortgage_payments = Column(Float, default=0.0)
    mean_home_improvement_and_repairs = Column(Float, default=0.0)
    mean_phone_and_internet = Column(Float, default=0.0)
    mean_gas_and_electricity = Column(Float, default=0.0)
    mean_water_sewer_and_garbage = Column(Float, default=0.0)
    mean_security = Column(Float, default=0.0)
    mean_hoa_fee = Column(Float, default=0.0)
    mean_property_tax = Column(Float, default=0.0)
    mean_other_housing_and_utilities = Column(Float, default=0.0)
    mean_medical = Column(Float, default=0.0)
    mean_pharmacy = Column(Float, default=0.0)
    mean_dental = Column(Float, default=0.0)
    mean_vision = Column(Float, default=0.0)
    mean_nursing = Column(Float, default=0.0)
    mean_fitness = Column(Float, default=0.0)
    mean_personal_care = Column(Float, default=0.0)
    mean_other_health_and_wellness = Column(Float, default=0.0)
    mean_gambling = Column(Float, default=0.0)
    mean_books_and_news = Column(Float, default=0.0)
    mean_movies_and_tv = Column(Float, default=0.0)
    mean_music_and_audio = Column(Float, default=0.0)
    mean_games = Column(Float, default=0.0)
    mean_events_and_recreation = Column(Float, default=0.0)
    mean_other_entertainment = Column(Float, default=0.0)
    mean_life_insurance = Column(Float, default=0.0)
    mean_health_insurance = Column(Float, default=0.0)
    mean_auto_insurance = Column(Float, default=0.0)
    mean_home_insurance = Column(Float, default=0.0)
    mean_other_insurance = Column(Float, default=0.0)
    mean_household_services = Column(Float, default=0.0)
    mean_education_services = Column(Float, default=0.0)
    mean_veterinary_services = Column(Float, default=0.0)
    mean_childcare_services = Column(Float, default=0.0)
    mean_digital_services = Column(Float, default=0.0)
    mean_legal_services = Column(Float, default=0.0)
    mean_financial_services = Column(Float, default=0.0)
    mean_shipping = Column(Float, default=0.0)
    mean_moving_and_storage = Column(Float, default=0.0)
    mean_other_services = Column(Float, default=0.0)
    mean_gas_and_ev_charging = Column(Float, default=0.0)
    mean_car_services = Column(Float, default=0.0)
    mean_public_transit = Column(Float, default=0.0)
    mean_taxi_and_ride_shares = Column(Float, default=0.0)
    mean_parking_and_tolls = Column(Float, default=0.0)
    mean_other_transportation = Column(Float, default=0.0)
    mean_flights = Column(Float, default=0.0)
    mean_hotels = Column(Float, default=0.0)
    mean_rental_cars = Column(Float, default=0.0)
    mean_other_travel = Column(Float, default=0.0)
    mean_tax_payments = Column(Float, default=0.0)
    mean_government_fees = Column(Float, default=0.0)
    mean_charity = Column(Float, default=0.0)
    mean_other_government_and_charity = Column(Float, default=0.0)

    # Count columns for each category - used for calculating number of transactions in each category for the month
    count_income = Column(Integer, default=0)
    count_transfers = Column(Integer, default=0)
    count_debt_payments = Column(Integer, default=0)
    count_investments = Column(Integer, default=0)
    count_bank_fees = Column(Integer, default=0)
    count_food_and_drink = Column(Integer, default=0)
    count_shopping = Column(Integer, default=0)
    count_housing_and_utilities = Column(Integer, default=0)
    count_health_and_wellness = Column(Integer, default=0)
    count_entertainment = Column(Integer, default=0)
    count_insurance = Column(Integer, default=0)
    count_services = Column(Integer, default=0)
    count_transportation = Column(Integer, default=0)
    count_travel = Column(Integer, default=0)
    count_government_and_charity = Column(Integer, default=0)
    count_other = Column(Integer, default=0)
    count_wages = Column(Integer, default=0)
    count_dividends = Column(Integer, default=0)
    count_interest = Column(Integer, default=0)
    count_benefits_and_pension = Column(Integer, default=0)
    count_tax_refunds = Column(Integer, default=0)
    count_unemployment = Column(Integer, default=0)
    count_other_income = Column(Integer, default=0)
    count_account_transfers = Column(Integer, default=0)
    count_investment_transfers = Column(Integer, default=0)
    count_savings_transfers = Column(Integer, default=0)
    count_cash_deposits = Column(Integer, default=0)
    count_cash_withdrawals = Column(Integer, default=0)
    count_loans_and_cash_advances = Column(Integer, default=0)
    count_person_to_person_payments = Column(Integer, default=0)
    count_other_transfers = Column(Integer, default=0)
    count_credit_card_payments = Column(Integer, default=0)
    count_auto_loan_payments = Column(Integer, default=0)
    count_student_loan_payments = Column(Integer, default=0)
    count_personal_loan_payments = Column(Integer, default=0)
    count_other_debt_payments = Column(Integer, default=0)
    count_buy = Column(Integer, default=0)
    count_sell = Column(Integer, default=0)
    count_atm_fees = Column(Integer, default=0)
    count_foreign_transaction_fees = Column(Integer, default=0)
    count_insufficient_funds = Column(Integer, default=0)
    count_interest_charge = Column(Integer, default=0)
    count_late_fees = Column(Integer, default=0)
    count_wire_fees = Column(Integer, default=0)
    count_overdraft_fees = Column(Integer, default=0)
    count_other_bank_fees = Column(Integer, default=0)
    count_restaurants_and_bars = Column(Integer, default=0)
    count_groceries = Column(Integer, default=0)
    count_coffee_shops = Column(Integer, default=0)
    count_liquor_stores = Column(Integer, default=0)
    count_other_food_and_drink = Column(Integer, default=0)
    count_clothing_and_accessories = Column(Integer, default=0)
    count_electronics = Column(Integer, default=0)
    count_pet_supplies = Column(Integer, default=0)
    count_gifts = Column(Integer, default=0)
    count_office_supplies = Column(Integer, default=0)
    count_sports_and_outdoors = Column(Integer, default=0)
    count_retail = Column(Integer, default=0)
    count_convenience_stores = Column(Integer, default=0)
    count_hair_and_beauty = Column(Integer, default=0)
    count_tabacco_and_vape = Column(Integer, default=0)
    count_other_shopping = Column(Integer, default=0)
    count_rent = Column(Integer, default=0)
    count_mortgage_payments = Column(Integer, default=0)
    count_home_improvement_and_repairs = Column(Integer, default=0)
    count_phone_and_internet = Column(Integer, default=0)
    count_gas_and_electricity = Column(Integer, default=0)
    count_water_sewer_and_garbage = Column(Integer, default=0)
    count_security = Column(Integer, default=0)
    count_hoa_fee = Column(Integer, default=0)
    count_property_tax = Column(Integer, default=0)
    count_other_housing_and_utilities = Column(Integer, default=0)
    count_medical = Column(Integer, default=0)
    count_pharmacy = Column(Integer, default=0)
    count_dental = Column(Integer, default=0)
    count_vision = Column(Integer, default=0)
    count_nursing = Column(Integer, default=0)
    count_fitness = Column(Integer, default=0)
    count_personal_care = Column(Integer, default=0)
    count_other_health_and_wellness = Column(Integer, default=0)
    count_gambling = Column(Integer, default=0)
    count_books_and_news = Column(Integer, default=0)
    count_movies_and_tv = Column(Integer, default=0)
    count_music_and_audio = Column(Integer, default=0)
    count_games = Column(Integer, default=0)
    count_events_and_recreation = Column(Integer, default=0)
    count_other_entertainment = Column(Integer, default=0)
    count_life_insurance = Column(Integer, default=0)
    count_health_insurance = Column(Integer, default=0)
    count_auto_insurance = Column(Integer, default=0)
    count_home_insurance = Column(Integer, default=0)
    count_other_insurance = Column(Integer, default=0)
    count_household_services = Column(Integer, default=0)
    count_education_services = Column(Integer, default=0)
    count_veterinary_services = Column(Integer, default=0)
    count_childcare_services = Column(Integer, default=0)
    count_digital_services = Column(Integer, default=0)
    count_legal_services = Column(Integer, default=0)
    count_financial_services = Column(Integer, default=0)
    count_shipping = Column(Integer, default=0)
    count_moving_and_storage = Column(Integer, default=0)
    count_other_services = Column(Integer, default=0)
    count_gas_and_ev_charging = Column(Integer, default=0)
    count_car_services = Column(Integer, default=0)
    count_public_transit = Column(Integer, default=0)
    count_taxi_and_ride_shares = Column(Integer, default=0)
    count_parking_and_tolls = Column(Integer, default=0)
    count_other_transportation = Column(Integer, default=0)
    count_flights = Column(Integer, default=0)
    count_hotels = Column(Integer, default=0)
    count_rental_cars = Column(Integer, default=0)
    count_other_travel = Column(Integer, default=0)
    count_tax_payments = Column(Integer, default=0)
    count_government_fees = Column(Integer, default=0)
    count_charity = Column(Integer, default=0)
    count_other_government_and_charity = Column(Integer, default=0)



summary_columns = [
    Field(column_name, column_name, column_type)
    for column_name, column_type in SummariesTable.get_column_python_types().items()
    if column_name != SummariesTable.id.name
]